"use client";

import { useState, type ReactNode } from "react";
import { DailyWeatherPanel } from "@/components/daily-weather-panel";

type Ferry = { dep: string; arr: string; relevance: string };
const SSL = "https://www.ssl.fo/en/timetable/ferry/7-suduroy-torshavn";
const hikeSources = [
  ["Øravík → Fámjin", "https://visitfaroeislands.com/en/whatson/hiking/hike/oravik-famjin"],
  ["Fámjin → Vágur", "https://visitfaroeislands.com/en/whatson/hiking/hike/famjin-vagur"],
  ["Øravík → Vágur", "https://visitfaroeislands.com/en/whatson/hiking/hike/oravik-vagur"],
];
const dayData = {
  1: { location: "Vágar / Tórshavn", lat: 62.0636, lon: -7.2772, hours: [16,17,18,19,20,21], implication: "Watch wind and low cloud around the flight and ferry connection.", history: "Vágar Airport began as a British wartime airfield in 1942; today it is the Faroes’ sole international airport. The route south then depends on the Smyril, the sea link that keeps Suðuroy connected to the capital.", places: "Vágar Airport → booked AirportTaxi → Farstøðin ferry terminal. Keep the ferry QR code, taxi confirmation and a Tórshavn fallback available offline.", contingency: "If RC 415’s delay makes the 21:15 ferry unsafe, do not rush the connection. Stay in Tórshavn and tell the host; use the next verified Route 7 sailing." },
  2: { location: "Øravík / Fámjin / Vágur", lat: 61.536, lon: -6.81, hours: [7,8,9,10,11,12,13,14,15,16,17,18], implication: "Low cloud, rain and gusts matter more than temperature across exposed passes.", history: "Øravík’s Tingstovan / Uppi millum Stovur is an old Suðuroy assembly site. Fámjin Church holds the original Merkið, the Faroese flag. Vágur grew through fishing and maritime industry; its hillside paths connect these settlements across the island’s old travel network.", places: "Fámjin Church and the original Merkið: allow a short respectful visit if open. Vágur is the practical lunch, resupply and road-transport bailout point. The planned routes pass Kirkjuvatn, Reyðabakki, Mittvatn, Ryskivatn, Hvannadal, Vágsskarð, Hovsdalur, Mannaskarð and Tingstovan.", contingency: "Decision 1: leave Øravík only with visibility, wind, rain, kit and group condition checked. Decision 2: at Fámjin, reassess pace/weather. Decision 3: at Vágur, complete the final mountain leg only if sound; otherwise arrange road transport. Komoot primary, Organic Maps backup; three GPX files offline; 112; waterproofs, warm layer, food, water, inhaler, first aid, blister care. Do not improvise a Borgarknappur summit route." },
  3: { location: "Tórshavn", lat: 62.0097, lon: -6.7716, hours: [7,8,9,10,11,14,15,16,17,18,19,20,21], implication: "Ferry disruption and gusts are more operationally important than the headline temperature.", history: "Ólavsøka is the Faroes’ national festival, tied to St Olaf, the opening of the Løgting parliamentary year, church services, sport, music and chain dancing. Tórshavn’s Tinganes peninsula is the historic seat of government. Treat the programme as live festival information rather than a fixed timetable.", places: "Tinganes, the harbour and food stalls are walkable from Farstøðin. Most normal shops may be closed for the public holiday; carry food, water and power.", contingency: "Choose 07:00 for the full day or 14:30 for the evening. Both plans rely on the 21:15 southbound return. Set a 20:20 leave-now alarm; missing it means an unplanned Tórshavn night." },
  4: { location: "Tórshavn / Tórsvøllur", lat: 62.018, lon: -6.78, hours: [6,8,10,11,12,13,14,15,16,17,18,19,20,21], implication: "A wet, gusty evening makes the stadium-to-ferry exit slower: preserve the return margin.", history: "Tórsvøllur is the Faroese national stadium in Gundadalur. The match sits within the country’s compact football culture, while the harbour and Tinganes show how Tórshavn grew around its protected bay and parliamentary core.", places: "Ferry terminal → Tinganes/harbour → Tórsvøllur is a short urban chain, but keep the exact walk and ticket/entry instructions offline. Have food before the ground rather than after full time.", contingency: "The 21:15 ferry is the only practical return. Extra time, a delayed exit, weather or disruption can break it; carry overnight essentials and leave the stadium in time for Farstøðin." },
  5: { location: "Sørvágur / Vágar", lat: 62.071, lon: -7.31, hours: [7,8,9,10,11,12,13,14,15,16,17,18], implication: "Trælanípan is visibility-dependent; fog removes the viewpoint and gusts matter at the cliff.", history: "Trælanípa means ‘Slave Cliff’. The story that enslaved people were thrown from it is local tradition/legend, not presented here as established fact. Its documented physical drama is the 142 m sea cliff, the ‘lake above the ocean’ optical illusion and Bøsdalafossur falling from Leitisvatn/Sørvágsvatn into the Atlantic.", places: "Primary optional activity only if the selected ferry-to-Sørvágur transfer and Hugo check-in leave 2½–3 hours plus transfer time. The official route is 7 km return; self-guided access is DKK 200 pp, check in/pay at the landowners’ reception. The operator currently lists guided hikes at DKK 600 pp, with a five-person minimum/equivalent and advance booking—not the older DKK 450 seed value.", contingency: "Do not force it into Friday. If the 07:00/16:00 ferry choice or onward connection makes it tight, leave it as a Saturday-morning impossibility rather than a rushed cliff walk. Confirm reception/opening and the exact taxi/bus transfer before committing." },
  6: { location: "Vágar Airport", lat: 62.0636, lon: -7.2772, hours: [6,7,8,9,10,11], implication: "Fog and low cloud can affect the morning flight; check status before leaving Sørvágur.", history: "Vágar Airport’s wartime origins explain its position on the island. The journey home then becomes a self-managed London airport transfer, with no airline protection between the two tickets.", places: "Guesthouse Hugo → Vágar Airport. Keep boarding passes, passport, charge cable, coach plan and insurance details in the day bag.", contingency: "If the Faroes flight is delayed, protect the separate Stansted flight rather than assuming airline assistance. Recheck airport transfer, flight status and the LGW → STN coach/rail option the night before." },
} as const;
const ferries: Record<number, { title: string; rows: Ferry[] }> = {
  3: { title: "Route 7 · Wednesday 29 July · Ólavsøka special timetable", rows: [
    { dep: "Krambatangi / Tvøroyri → Tórshavn · 07:00", arr: "~09:05", relevance: "Option A · full national day" }, { dep: "Tórshavn → Krambatangi / Tvøroyri · 11:30", arr: "~13:35", relevance: "Published southbound; not your plan" }, { dep: "Krambatangi / Tvøroyri → Tórshavn · 14:30", arr: "~16:35", relevance: "Option B · compact evening" }, { dep: "Tórshavn → Krambatangi / Tvøroyri · 21:15", arr: "~23:20", relevance: "Planned return / last useful sailing" },
  ] },
  4: { title: "Route 7 · Thursday 30 July", rows: [
    { dep: "Krambatangi / Tvøroyri → Tórshavn · 06:00", arr: "08:05", relevance: "Published · too early" }, { dep: "Tórshavn → Krambatangi / Tvøroyri · 08:45", arr: "10:50", relevance: "Published southbound" }, { dep: "Krambatangi / Tvøroyri → Tórshavn · 11:30", arr: "13:35", relevance: "Planned match outbound" }, { dep: "Tórshavn → Krambatangi / Tvøroyri · 14:15", arr: "16:20", relevance: "Published southbound" }, { dep: "Krambatangi / Tvøroyri → Tórshavn · 17:30", arr: "19:35", relevance: "Too late for kick-off" }, { dep: "Tórshavn → Krambatangi / Tvøroyri · 21:15", arr: "23:20", relevance: "Planned return / final sailing" },
  ] },
};

export function DailyContextTabs({ day }: { day: 1|2|3|4|5|6 }) {
  const [active, setActive] = useState("weather"); const data = dayData[day]; const timetable = ferries[day];
  const tabs = ["weather", ...(timetable ? ["transport"] : []), "history & context", "places", "contingencies"];
  return <section className="px-4 sm:px-8 lg:px-12 pb-20 max-w-[1280px] mx-auto">
    <div className="border-t border-basalt/15 pt-8"><p className="label text-rust">Field context</p><h2 className="mt-2 text-[clamp(1.35rem,3vw,2rem)] text-basalt" style={{ fontFamily: "var(--font-cinzel)" }}>Useful detail, kept out of the running order</h2></div>
    <div className="mt-5 flex gap-2 overflow-x-auto pb-1" role="tablist">{tabs.map((tab) => <button key={tab} role="tab" aria-selected={active === tab} onClick={() => setActive(tab)} className={`shrink-0 px-3 py-2 text-[12px] capitalize border transition-colors focus-visible:outline-2 focus-visible:outline-fjord ${active === tab ? "border-fjord bg-fjord text-wool" : "border-basalt/20 text-basalt/65 hover:border-fjord/50"}`}>{tab}</button>)}</div>
    <div className="mt-4" role="tabpanel">{active === "weather" && <DailyWeatherPanel date={["", "2026-07-27", "2026-07-28", "2026-07-29", "2026-07-30", "2026-07-31", "2026-08-01"][day]} location={data.location} lat={data.lat} lon={data.lon} activityHours={[...data.hours]} implication={data.implication} />}{active === "transport" && timetable && <TransportTable title={timetable.title} rows={timetable.rows} />}{active === "history & context" && <Panel title="History & context"><p>{data.history}</p>{day === 2 && <p className="mt-3">Read the official route notes: {hikeSources.map(([label, href], index) => <span key={href}>{index ? " · " : ""}<a className="text-fjord underline underline-offset-4" href={href} target="_blank" rel="noreferrer">{label}</a></span>)}</p>}{day === 5 && <p className="mt-3">Source: <a className="text-fjord underline underline-offset-4" href="https://visitfaroeislands.com/en/whatson/places/place/tralanipan0?lang=en" target="_blank" rel="noreferrer">Visit Faroe Islands</a>; fee/access: <a className="text-fjord underline underline-offset-4" href="https://www.tralanipan.fo/information-and-guidance" target="_blank" rel="noreferrer">Trælanípan operator</a>.</p>}</Panel>}{active === "places" && <Panel title="Places, supplies & practical use"><p>{data.places}</p></Panel>}{active === "contingencies" && <Panel title="Contingency"><p>{data.contingency}</p></Panel>}</div>
  </section>;
}
function Panel({ title, children }: { title: string; children: ReactNode }) { return <article className="border border-basalt/15 rounded-[8px] p-5 max-w-[60rem] text-[14px] leading-relaxed text-basalt/75"><h3 className="text-[15px] font-medium text-basalt">{title}</h3><div className="mt-2">{children}</div><p className="mt-4 pt-3 border-t border-basalt/10 text-[11px] text-basalt/50">Context checked 26 July 2026 · verify live conditions and operating hours before leaving.</p></article>; }
function TransportTable({ title, rows }: { title: string; rows: Ferry[] }) { return <article className="border border-basalt/15 rounded-[8px] overflow-hidden max-w-[60rem]"><div className="p-4 border-b border-basalt/10"><p className="label text-fjord">{title}</p><p className="mt-1 text-[12px] text-basalt/65">M/F Smyril · approx. 2h 05m. Krambatangi is the terminal near Tvøroyri—not the village itself.</p></div><div className="overflow-x-auto"><table className="min-w-[42rem] w-full text-left text-[13px]"><thead className="text-[11px] text-basalt/50"><tr><th className="p-3">Departure</th><th>Expected arrival</th><th>Itinerary use</th></tr></thead><tbody>{rows.map((row) => <tr key={row.dep} className="border-t border-basalt/10"><td className="p-3 code text-fjord">{row.dep}</td><td className="code">{row.arr}</td><td className="text-basalt/70">{row.relevance}</td></tr>)}</tbody></table></div><div className="p-4 border-t border-basalt/10 text-[12px] leading-relaxed text-basalt/65">Foot passengers need a valid ticket. Arrive with a safety margin; the gate closes shortly before departure (the current plan uses 5 minutes, but verify). Weather/operational changes can alter sailings. <a href={SSL} className="text-fjord underline underline-offset-4" target="_blank" rel="noreferrer">Verify live timetable ↗</a> · booking: <a href="https://booking.ssl.fo" className="text-fjord underline underline-offset-4" target="_blank" rel="noreferrer">booking.ssl.fo</a> · SSL route information: +298 343030 · Last checked 26 July 2026.</div></article>; }
